### ISSUE TITLE
Investigate tonic error when socket is closed by the client side

### ISSUE THREAD

**Issue by sdaveas** [axelarnetwork/tofnd#167]
When the socket is closed by the client, instead of a `None` message, we sometimes get `Some` message containing the error "error reading a body from connection: protocol error: not a result of an error".

https://github.com/axelarnetwork/tofnd/blob/d09b995d454e2abfc1250a5076b2e2087e064165/src/gg20/broadcast.rs#L71-L78
 
This has been changed to a `debug!` message for now, so we don't pollute the log output with false-positive error messages, but will need to find out why this happens.

**Comment by milapsheth** [comment]
n/a
