### ISSUE TITLE
Investigate if we can use `scrypt` functionalities to hash and/or produce salt

### ISSUE THREAD

**Issue by sdaveas** [axelarnetwork/tofnd#190]
Something I noticed but did not have time to follow up: `scrypt` [also supports](https://docs.rs/scrypt) the `PasswordHasher` trait from RustCrypto.  That trait provides types for salt, password hash, etc.  In this PR I basically re-invented my own custom types for these things.  It might be cooler to use `PasswordHasher` types but I didn't have time to figure out how it all works.

_Originally posted by @ggutoski in https://github.com/axelarnetwork/tofnd/pull/187#issuecomment-924948921_

**Comment by milapsheth** [comment]
moved to jira
