### ISSUE TITLE
Prune off old keygen data from the kvstore

### ISSUE THREAD

**Issue by milapsheth** [axelarnetwork/tofnd#202]
axelar-core only keeps around the last 8 keys from rotation. So, we don't need to store really old keygen data in the kvstore. Estimate how much size each keygen takes in the kvstore, and what would be a good cutoff (e.g. 100? 1000? etc.)

**Comment by ggutoski** [comment]
As a last resort we can use on-chain key recovery to recover old keys, provided the user hasn't lost her mnemonic.

I wonder whether there's a potential use for HD (hierarchical deterministic) key generation here?  (See the [BIP32 spec](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) for info in the non-threshold case as applied to Bitcoin.)  This might allow another way to recover old keys as a redundant alternative to on-chain key recovery.

**Comment by milapsheth** [comment]
n/a now
