### ISSUE TITLE
Remove dublicate `Entropy` and `Password` structs

### ISSUE THREAD

**Issue by sdaveas** [axelarnetwork/tofnd#215]
https://github.com/axelarnetwork/tofnd/blob/117a35b808663ceebfdd6e6582a3f0a037151198/src/gg20/types.rs#L71-L73

and 

https://github.com/axelarnetwork/tofnd/blob/117a35b808663ceebfdd6e6582a3f0a037151198/src/encrypted_sled/password.rs#L11-L13

**Comment by milapsheth** [comment]
done
