### ISSUE TITLE
No version information is output when running 'tofnd --version'

### ISSUE THREAD

**Issue by Pete-LunaNova** [axelarnetwork/tofnd#225]
## Description/Reasoning
It is important to be able to check which version of tofnd is currently installed. Validators using "infrastructure as code" tools, such as ansible, will want to use scripts that evaluate the version installed before making any modifications to the state of their infrastructure.

## Current Behaviour
Running `tofnd --version` just outputs the string `tofnd`.

## Expected Behaviour
Running `tofnd --version` should output version information in a standardized format that can be reliably parsed by automated systems.

**Comment by ggutoski** [comment]
@Pete-LunaNova any particular standardized format you recommend?  (A link would be great.)

**Comment by Pete-LunaNova** [comment]
I think the best approach is to keep it simple and have the binary name followed by a space and then the exact version string that is used to tag the release on git eg.:
`tofnd v0.7.1`

2 things that are important:

1) Once an output format is settled upon, keep it consistent and don't change it unless there's a very good reason and it's communicated clearly, as it may end up breaking all sorts of automation.

2) Ensure there are proper processes in place so that this version output always tracks the version tag that is being used for releases. I have seen some projects inadvertently release new versions without a good process in place and it causes no end of confusion when the version info returned by the software is inaccurate.
