### ISSUE TITLE
Block release if version in cargo.toml mismatches

### ISSUE THREAD

**Issue by talalashraf** [axelarnetwork/tofnd#234]
The community has complained about this. We need to make sure our release process doesn't continue if we use the incorrect version in the cargo.toml file. I think we should just add a commit in the pipeline that updates this.

**Comment by milapsheth** [comment]
That would be nice, looks like the version in Cargo.toml is already outdated :(

**Comment by sdaveas** [comment]
related to https://github.com/axelarnetwork/tofnd/issues/227

**Comment by talalashraf** [comment]
https://github.com/axelarnetwork/playground/blob/main/.github/workflows/release.yaml
