### ISSUE TITLE
Don't log logical errors regarding already reserved mnemonic

### ISSUE THREAD

**Issue by sdaveas** [axelarnetwork/tofnd#250]
In addition to #228, we need to eliminate `mnemonic already reserved` error logs because they trigger pagerduty alerts. Other than logging these errors, tofnd binary needs not to return a `TofndError` from main because these results are also captured by datadog.
For example, [here](https://app.datadoghq.com/logs?query=service%3Atofnd%20status%3Aerror&cols=host%2Cservice&context_event=AQAAAX4CAjXcFEKCHwAAAABBWDRDQWs3SkFBQ2ZBVXg5MDlVSFpBQWs&event=AQAAAX3k1eg-La12CgAAAABBWDNrMWZ2T0FBQkttRkFDQWJfWFVnQVI&index=&messageDisplay=inline&stream_sort=desc&viz=&from_ts=1640113431702&to_ts=1640718231702&live=true) is the message logged by tofnd, and [here](https://app.datadoghq.com/logs?query=service%3Atofnd%20status%3Aerror&cols=host%2Cservice&context_event=AQAAAX4CAjXcFEKCHwAAAABBWDRDQWs3SkFBQ2ZBVXg5MDlVSFpBQWs&event=AQAAAX3k1eg-La12DAAAAABBWDNrMWZ2T0FBQkttRkFDQWJfWFVnQVQ&index=&messageDisplay=inline&stream_sort=desc&viz=&from_ts=1640113431702&to_ts=1640718231702&live=true) is a the same message as the return value of the binary (notice the "Error:" prefix).

However, we can't always return `Ok(())` because the `auto` command relies on the results of `-m import` and `-m create` (ie if `import` succeeds, proceed, else try to `create`).

One approach is to replace `TofndResult` with exit codes, (https://docs.rs/exitcode/latest/exitcode/ crate might be useful).

# ⚠️ Attention 
For users that rely on tofnd's returning messages or mnemonic reserve `Error` errors, this is a breaking change.

**Comment by ggutoski** [comment]
Could we instead add a `-m auto` flag to tofnd and do everything inside the executable?

**Comment by milapsheth** [comment]
Instead of changing tofnd, we decided that the entrypoint script will perform a command based on the state of the kvstore (similar to the launch validator with binaries script) and ask the user to explicitly backup their mnemonics. See #252 and axelarnetwork/axelarate-community#268.
