### ISSUE TITLE
Clarify "Address already in use (os error 98)" error message

### ISSUE THREAD

**Issue by ggutoski** [axelarnetwork/tofnd#268]
Run tofnd on a system with tofnd already running:
```
$ tofnd
Please type your tofnd password:

Error: Address already in use (os error 98)
```
This error message is confusing.  `Address already in use` does not appear in tofnd code base.

Talal's diagnosis is that the new tofnd process is trying to bind to a port that's already in use by the existing tofnd process.  This error message is from the OS.

We should add some colour to OS error messages.

**Comment by milapsheth** [comment]
moved to jira
