### ISSUE TITLE
Tofnd arm64 binaries are actually amd64

### ISSUE THREAD

**Issue by talalashraf** [axelarnetwork/tofnd#294]
tofnd arm64 binaries are currently amd64 binaries, we need to make sure the binaries are built appropriately

**Comment by kalidax** [comment]
Yes indeed,

I did not remove the arm in the matrix (currently github does not support ARM)
- We can have a hosted ARM runner. 
- We can  cross compile with cargo like we did for core (in GO). 
Second option is better if it is only for multi arch support.
I will have a looks asap

**Comment by kalidax** [comment]
I taked to @milapsheth 

we can remove the ARM binaries from the release page for the moment and build them manually as @talalashraf used to do
