### ISSUE TITLE
Custom config parameters for tofn malicious behaviours

### ISSUE THREAD

**Issue by ggutoski** [axelarnetwork/tofnd#54]
Tofnd allows the end-user to specify a malicious behaviour in a config file or CLI flag.  We currently enforce that all malicious behaviours include a `victim` arg, even those malicious variants that do not have a `victim` arg.  For those variants, the `victim` arg is simply ignored:

* https://github.com/axelarnetwork/tofnd/blob/192d95441ebba70024826939b9187da0ff179642/src/config/mod.rs#L71
* https://github.com/axelarnetwork/tofnd/blob/192d95441ebba70024826939b9187da0ff179642/src/config/mod.rs#L91

We do this only because it's easy.  Instead, we should demand a `victim` arg only for those malicious variants that actually need it.

In general, each malicious variant might have ts own custom args list.  For each such variant, we'll need to write custom code to parse config data for that variant. That could become tedious in the future but we should do it anyway.  See discussion in axelarnetwork/tofn#38.

**Comment by milapsheth** [comment]
n/a
