### ISSUE TITLE
Support keygen crime parsing

### ISSUE THREAD

**Issue by sdaveas** [axelarnetwork/tofnd#83]
In https://github.com/axelarnetwork/tofnd/blob/main/src/config/mod.rs, we support command line parsing for sign malicious types. When keygen crimes are accommodated, we need to to extend this config for keygen behaviours, as well.

This config file is already ugly, so that could be a good chance to refactor it. Maybe it'd be cleaner if we use a config file instead of command line args.

**Comment by milapsheth** [comment]
n/a
