### ISSUE TITLE
don't expect results of malicious parties in tests

### ISSUE THREAD

**Issue by sdaveas** [axelarnetwork/tofnd#88]
When a crime is detected, parties can immediately stop the execution of the protocol. Although this is expected behaviour from tofn's side, our test framework in tofnd expect all threads to return. This causes some issues. The problem manifests when criminals are exposed, honest parties stop, but criminals still wait for messages. The result is that some tests are running for ever.

A temporary hacky solution is to make criminals have multiple shares. That way each one of the criminal shares can notify the other that the protocol is over. A proper solution is to decouple the data that are related to the protocol and the ones that are related to the communication inside `Party` struct.

https://github.com/axelarnetwork/tofnd/blob/41794513bba95e41f90ea03ca1df1dfb206198a3/src/tests/tofnd_party.rs#L16-L24

When this is done, we will not need to wait threads to return in order to reclaim their resources (as done below).

https://github.com/axelarnetwork/tofnd/blob/41794513bba95e41f90ea03ca1df1dfb206198a3/src/tests/mod.rs#L467-L474

**Comment by milapsheth** [comment]
n/a
